# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: CopyFiles@2
  inputs:
    contents: |
      **/public/**
      firebase.json
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy public site files'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'